// Contract PDF generator – produces a standards-compliant PDF-1.4 document.
// Keep this file server-safe (no browser APIs used).

type ContractData = {
  hostelName: string;
  hostelAddress: string;
  studentName: string;
  phone: string;
  email?: string;
  roomNumber: string;
  securityDeposit: number;
  contractDuration: number;
  admissionDate: string;
  generatedDate: string;
};

/** Escape PDF string special characters. */
const esc = (s: string) => String(s ?? '').replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');

function wrap(text: string, maxChars = 80): string[] {
  const words = text.split(' ');
  const lines: string[] = [];
  let cur = '';
  for (const w of words) {
    if ((cur + ' ' + w).trim().length <= maxChars) {
      cur = (cur + ' ' + w).trim();
    } else {
      if (cur) lines.push(cur);
      cur = w;
    }
  }
  if (cur) lines.push(cur);
  return lines;
}

export function contractPdf(data: ContractData): Uint8Array {
  const ops: string[] = ['BT'];

  const at = (x: number, y: number, size: number, text: string) =>
    [`/F1 ${size} Tf`, `${x} ${y} Td`, `(${esc(text)}) Tj`, `0 0 Td`];

  let y = 780;
  const LEFT = 60;
  const RIGHT_COL = 320;
  const LINE = 18;

  const line = (size: number, text: string, x = LEFT) => {
    ops.push(...at(x, y, size, text));
    y -= LINE;
  };

  const section = (title: string) => {
    y -= 6;
    ops.push(...at(LEFT, y, 10, title));
    y -= 4;
    ops.push(...at(LEFT, y, 8, '─'.repeat(90).slice(0, 80)));
    y -= LINE - 4;
  };

  const field = (label: string, value: string) => {
    ops.push(...at(LEFT, y, 9, label + ':'));
    ops.push(...at(RIGHT_COL, y, 9, value));
    y -= LINE;
  };

  // Title block
  ops.push(`/F1 16 Tf`, `${LEFT} ${y} Td`, `(${esc('HOSTEL RESIDENCY AGREEMENT')}) Tj`, `0 0 Td`);
  y -= 26;
  ops.push(`/F1 10 Tf`, `${LEFT} ${y} Td`, `(This agreement is made between the hostel owner and the resident named below.) Tj`, `0 0 Td`);
  y -= LINE * 2;

  section('1. HOSTEL INFORMATION');
  field('Hostel Name', data.hostelName);
  field('Address', data.hostelAddress || 'Not recorded');
  y -= 4;

  section('2. RESIDENT INFORMATION');
  field('Full Name', data.studentName);
  field('Phone Number', data.phone);
  field('Email Address', data.email || 'Not provided');
  y -= 4;

  section('3. ROOM INFORMATION');
  field('Room Number', data.roomNumber);
  field('Admission Date', data.admissionDate);
  y -= 4;

  section('4. FINANCIAL TERMS');
  field('Security Deposit', `Rs. ${Number(data.securityDeposit).toLocaleString('en-IN')}`);
  field('Contract Duration', `${data.contractDuration} month(s)`);
  y -= 4;

  section('5. CONTRACT PERIOD');
  field('Contract Start', data.admissionDate);
  field('Document Generated', data.generatedDate);
  y -= 4;

  section('6. TERMS & CONDITIONS');
  const terms = [
    'The resident agrees to abide by all hostel rules and regulations.',
    'Rent is due as agreed with the hostel owner.',
    'The security deposit is refundable at move-out, subject to deductions for',
    '  damages beyond normal wear, outstanding dues, and hostel policy.',
    'The resident must provide advance notice before vacating the room.',
    'Subletting or transferring this agreement is not permitted.',
    'The hostel owner reserves the right to terminate this agreement for',
    '  violation of hostel rules, non-payment, or illegal activity.',
  ];
  for (const t of terms) {
    ops.push(`/F1 9 Tf`, `${LEFT} ${y} Td`, `(${esc(t)}) Tj`, `0 0 Td`);
    y -= LINE - 2;
  }
  y -= 8;

  section('7. SIGNATURES');
  y -= 6;
  ops.push(`/F1 9 Tf`, `${LEFT} ${y} Td`, `(Owner / Hostel Manager) Tj`, `0 0 Td`);
  ops.push(`/F1 9 Tf`, `${RIGHT_COL} ${y} Td`, `(Resident) Tj`, `0 0 Td`);
  y -= 36;
  ops.push(`/F1 9 Tf`, `${LEFT} ${y} Td`, `(Signature: ______________________________) Tj`, `0 0 Td`);
  ops.push(`/F1 9 Tf`, `${RIGHT_COL} ${y} Td`, `(Signature: ______________________________) Tj`, `0 0 Td`);
  y -= LINE;
  ops.push(`/F1 9 Tf`, `${LEFT} ${y} Td`, `(Name: __________________________________) Tj`, `0 0 Td`);
  ops.push(`/F1 9 Tf`, `${RIGHT_COL} ${y} Td`, `(Name: ${esc(data.studentName)}) Tj`, `0 0 Td`);
  y -= LINE;
  ops.push(`/F1 9 Tf`, `${LEFT} ${y} Td`, `(Date:  _____ / _____ / _________) Tj`, `0 0 Td`);
  ops.push(`/F1 9 Tf`, `${RIGHT_COL} ${y} Td`, `(Date:  _____ / _____ / _________) Tj`, `0 0 Td`);
  y -= LINE * 2;
  ops.push(`/F1 8 Tf`, `${LEFT} ${y} Td`, `(This document was generated by Roomly on ${esc(data.generatedDate)}.) Tj`, `0 0 Td`);

  ops.push('ET');
  const stream = ops.join('\n');

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
  ];

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [0];
  objects.forEach((obj, i) => {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${obj}\nendobj\n`;
  });

  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';
  pdf += offsets.slice(1).map(x => String(x).padStart(10, '0') + ' 00000 n ').join('\n');
  pdf += `\ntrailer << /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return new TextEncoder().encode(pdf);
}
