-- HostelFlow complete schema. Run once in Supabase SQL Editor.
create extension if not exists pgcrypto;
create type public.user_role as enum ('owner','student');
create type public.student_status as enum ('pending','active','inactive');
create type public.payment_status as enum ('due','partial','paid','overdue');
create type public.complaint_status as enum ('open','resolved');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, role public.user_role not null, full_name text not null default '', created_at timestamptz not null default now());
create table public.owners (id uuid primary key references auth.users(id) on delete cascade, business_name text, created_at timestamptz not null default now());
create table public.hostels (id uuid primary key default gen_random_uuid(), owner_id uuid not null references public.owners(id) on delete cascade, name text not null, address text not null default '', registration_token uuid not null default gen_random_uuid() unique, created_at timestamptz not null default now());
create table public.floors (id uuid primary key default gen_random_uuid(), hostel_id uuid not null references public.hostels(id) on delete cascade, number integer not null, unique(hostel_id,number));
create table public.rooms (id uuid primary key default gen_random_uuid(), hostel_id uuid not null references public.hostels(id) on delete cascade, floor_id uuid references public.floors(id) on delete set null, room_number text not null, bed_capacity integer not null check(bed_capacity > 0), is_ac boolean not null default false, rent_amount numeric(12,2) not null check(rent_amount >= 0), created_at timestamptz not null default now(), unique(hostel_id,room_number));
create table public.students (id uuid primary key default gen_random_uuid(), owner_id uuid not null references public.owners(id) on delete cascade, hostel_id uuid not null references public.hostels(id), auth_user_id uuid unique references auth.users(id) on delete set null, full_name text not null, email text, phone text not null, whatsapp_number text, admission_date date not null default current_date, security_deposit numeric(12,2) not null default 0, deposit_duration_months integer not null default 0, contract_duration_months integer not null default 11, status public.student_status not null default 'active', created_at timestamptz not null default now(), unique(owner_id,phone));
create table public.room_assignments (id uuid primary key default gen_random_uuid(), student_id uuid not null references public.students(id) on delete cascade, room_id uuid not null references public.rooms(id), moved_in_at timestamptz not null default now(), moved_out_at timestamptz, check(moved_out_at is null or moved_out_at >= moved_in_at));
create unique index one_current_room_per_student on public.room_assignments(student_id) where moved_out_at is null;
create table public.pending_admissions (id uuid primary key default gen_random_uuid(), hostel_id uuid not null references public.hostels(id) on delete cascade, full_name text not null, email text, phone text not null, whatsapp_number text, requested_at timestamptz not null default now(), reviewed_at timestamptz, rejected_at timestamptz, unique(hostel_id,phone));
create table public.rent_payments (id uuid primary key default gen_random_uuid(), student_id uuid not null references public.students(id) on delete restrict, period date not null, amount_due numeric(12,2) not null check(amount_due>=0), amount_paid numeric(12,2) not null default 0 check(amount_paid>=0), due_date date not null, paid_at timestamptz, status public.payment_status not null default 'due', created_at timestamptz not null default now(), unique(student_id,period));
create table public.contracts (id uuid primary key default gen_random_uuid(), student_id uuid not null references public.students(id) on delete restrict, storage_path text not null, security_deposit numeric(12,2) not null, deposit_duration_months integer not null, contract_duration_months integer not null, generated_at timestamptz not null default now());
create table public.complaints (id uuid primary key default gen_random_uuid(), student_id uuid not null references public.students(id) on delete restrict, description text not null check(char_length(description)>0), photo_path text, status public.complaint_status not null default 'open', created_at timestamptz not null default now(), resolved_at timestamptz);
create index students_hostel_idx on public.students(hostel_id); create index rooms_hostel_idx on public.rooms(hostel_id); create index complaints_student_idx on public.complaints(student_id); create index rent_status_idx on public.rent_payments(status,due_date); create index assignments_room_idx on public.room_assignments(room_id) where moved_out_at is null;

create or replace function public.is_owner() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from profiles where id=auth.uid() and role='owner')$$;
create or replace function public.owns_hostel(h uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from hostels where id=h and owner_id=auth.uid())$$;
create or replace function public.owns_student(s uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from students where id=s and owner_id=auth.uid())$$;
create or replace function public.is_self_student(s uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from students where id=s and auth_user_id=auth.uid())$$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into profiles(id,role,full_name) values(new.id,coalesce((new.raw_user_meta_data->>'role')::public.user_role,'student'),coalesce(new.raw_user_meta_data->>'full_name','')); if coalesce(new.raw_user_meta_data->>'role','student')='owner' then insert into owners(id,business_name) values(new.id,new.raw_user_meta_data->>'business_name'); end if; return new; end$$;
create trigger auth_user_profile after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.available_beds(room uuid) returns integer language sql stable security definer set search_path=public as $$
  select r.bed_capacity - count(distinct s.id)::integer
  from rooms r
  left join room_assignments a on a.room_id = r.id and a.moved_out_at is null
  left join students s on s.id = a.student_id and s.status = 'active'
  where r.id = room
  group by r.id, r.bed_capacity;
$$;
create or replace function public.assign_room(p_student uuid,p_room uuid) returns void language plpgsql security definer set search_path=public as $$declare target_owner uuid; begin select owner_id into target_owner from students where id=p_student; if target_owner is null or target_owner<>auth.uid() or not exists(select 1 from rooms r join hostels h on h.id=r.hostel_id where r.id=p_room and h.owner_id=auth.uid()) then raise exception 'Not allowed'; end if; if public.available_beds(p_room)<=0 then raise exception 'Room is full'; end if; update room_assignments set moved_out_at=now() where student_id=p_student and moved_out_at is null; insert into room_assignments(student_id,room_id) values(p_student,p_room); end$$;
create or replace function public.approve_admission(p_pending uuid,p_room uuid) returns uuid language plpgsql security definer set search_path=public as $$declare p pending_admissions; sid uuid; oid uuid; begin select * into p from pending_admissions where id=p_pending and reviewed_at is null and rejected_at is null for update; if p.id is null or not public.owns_hostel(p.hostel_id) then raise exception 'Not allowed'; end if; select owner_id into oid from hostels where id=p.hostel_id; insert into students(owner_id,hostel_id,full_name,email,phone,whatsapp_number,status) values(oid,p.hostel_id,p.full_name,p.email,p.phone,coalesce(p.whatsapp_number,p.phone),'active') returning id into sid; perform public.assign_room(sid,p_room); update pending_admissions set reviewed_at=now() where id=p.id; return sid; end$$;
create or replace function public.submit_admission(p_hostel uuid,p_name text,p_email text,p_phone text,p_whatsapp text) returns uuid language plpgsql security definer set search_path=public as $$declare v uuid; begin if not exists(select 1 from hostels where id=p_hostel) then raise exception 'Hostel not found'; end if; if exists(select 1 from students where hostel_id=p_hostel and phone=p_phone and status<>'inactive') or exists(select 1 from pending_admissions where hostel_id=p_hostel and phone=p_phone and reviewed_at is null and rejected_at is null) then raise exception 'An application using this phone number already exists'; end if; insert into pending_admissions(hostel_id,full_name,email,phone,whatsapp_number) values(p_hostel,trim(p_name),nullif(trim(p_email),''),trim(p_phone),nullif(trim(p_whatsapp),'')) returning id into v; return v; end$$;
grant execute on function public.submit_admission(uuid,text,text,text,text) to anon, authenticated; grant execute on function public.assign_room(uuid,uuid), public.approve_admission(uuid,uuid), public.available_beds(uuid) to authenticated;

alter table public.profiles enable row level security; alter table public.owners enable row level security; alter table public.hostels enable row level security; alter table public.floors enable row level security; alter table public.rooms enable row level security; alter table public.students enable row level security; alter table public.room_assignments enable row level security; alter table public.pending_admissions enable row level security; alter table public.rent_payments enable row level security; alter table public.contracts enable row level security; alter table public.complaints enable row level security;
create policy profiles_self on profiles for select using(id=auth.uid()); create policy owners_self on owners for all using(id=auth.uid()) with check(id=auth.uid());
create policy hostels_owner on hostels for all using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy floors_owner on floors for all using(owns_hostel(hostel_id)) with check(owns_hostel(hostel_id)); create policy rooms_owner_read on rooms for select using(owns_hostel(hostel_id)); create policy rooms_owner_write on rooms for all using(owns_hostel(hostel_id)) with check(owns_hostel(hostel_id));
create policy students_owner on students for all using(owner_id=auth.uid()) with check(owner_id=auth.uid()); create policy students_self_read on students for select using(auth_user_id=auth.uid());
create policy assignments_owner on room_assignments for all using(owns_student(student_id)) with check(owns_student(student_id)); create policy assignments_self_read on room_assignments for select using(is_self_student(student_id));
create policy admissions_owner on pending_admissions for all using(owns_hostel(hostel_id)) with check(owns_hostel(hostel_id));
create policy payments_owner on rent_payments for all using(owns_student(student_id)) with check(owns_student(student_id)); create policy payments_self_read on rent_payments for select using(is_self_student(student_id));
create policy contracts_owner on contracts for all using(owns_student(student_id)) with check(owns_student(student_id)); create policy contracts_self_read on contracts for select using(is_self_student(student_id));
create policy complaints_owner on complaints for all using(owns_student(student_id)) with check(owns_student(student_id)); create policy complaints_student_read on complaints for select using(is_self_student(student_id)); create policy complaints_student_insert on complaints for insert with check(is_self_student(student_id));

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values ('complaint-photos','complaint-photos',false,5242880,array['image/jpeg','image/png','image/webp']),('contracts','contracts',false,10485760,array['application/pdf']) on conflict(id) do nothing;
create policy complaint_upload on storage.objects for insert to authenticated with check(bucket_id='complaint-photos' and (storage.foldername(name))[1]=auth.uid()::text); create policy complaint_read on storage.objects for select to authenticated using(bucket_id='complaint-photos' and exists(select 1 from complaints c where c.photo_path=name and (is_self_student(c.student_id) or owns_student(c.student_id)))); create policy contract_read on storage.objects for select to authenticated using(bucket_id='contracts' and exists(select 1 from contracts c where c.storage_path=name and (is_self_student(c.student_id) or owns_student(c.student_id))));
